import type { Metadata } from 'next'
import Script from 'next/script'
import Link from 'next/link'
import { Geist, Geist_Mono } from 'next/font/google'
import { Flame } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { NavDropdown } from '@/components/nav-dropdown'
import './globals.css'

const GA_ID = process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID
const APP_URL = process.env.NEXT_PUBLIC_APP_URL ?? 'https://app.firesafe.ai'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: {
    template: '%s — FireSafe.AI',
    default: 'FireSafe.AI — AI Tools for Fire Protection Engineering',
  },
  description:
    'AI-powered fire protection engineering tools: FDS/CFD modeling, smoke control analysis, egress calculations, code consulting, sprinkler design, and more. Built for CFPEs on NFPA, IBC, and IFC standards.',
  keywords: [
    'fire protection engineering software',
    'AI fire protection',
    'FDS modeling software',
    'smoke control analysis',
    'ASET RSET calculator',
    'NFPA 13 sprinkler design',
    'fire code comparison',
  ],
  metadataBase: new URL('https://firesafe.ai'),
  openGraph: {
    type: 'website',
    siteName: 'FireSafe.AI',
    title: 'FireSafe.AI — AI Tools for Fire Protection Engineering',
    description:
      'AI-powered fire protection engineering tools built on NFPA, IBC, and IFC standards.',
  },
  robots: {
    index: true,
    follow: true,
  },
}

const toolLinks = [
  { name: 'FDS/CFD Modeling', href: '/tools/fds-cfd' },
  { name: 'Smoke Control', href: '/tools/smoke-control' },
  { name: 'Egress Analysis', href: '/tools/egress' },
  { name: 'CodeCompare', href: APP_URL },
  { name: 'Code Consulting', href: '/tools/code-consulting' },
  { name: 'Fire Detection', href: '/tools/fire-detection' },
  { name: 'Suppression Systems', href: '/tools/suppression' },
  { name: 'HazMat & Risk', href: '/tools/hazmat-risk' },
  { name: 'StoragePro', href: '/tools/storagepro' },
  { name: 'PE Tutor', href: '/tools/pe-tutor' },
]

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      {GA_ID && (
        <>
          <Script src={`https://www.googletagmanager.com/gtag/js?id=${GA_ID}`} strategy="afterInteractive" />
          <Script id="gtag-init" strategy="afterInteractive">
            {`window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments);}gtag('js',new Date());gtag('config','${GA_ID}');`}
          </Script>
        </>
      )}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen bg-background">
          <nav className="fixed top-0 z-50 w-full border-b border-border bg-background/92 backdrop-blur-xl backdrop-saturate-[1.4]">
            <div className="mx-auto flex h-16 max-w-6xl items-center justify-between px-6">
              {/* Logo */}
              <Link href="/" className="flex items-center gap-2.5">
                <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-primary/10 ring-1 ring-primary/30">
                  <Flame className="h-4.5 w-4.5 text-primary" />
                </div>
                <span className="text-sm font-bold tracking-tight">FireSafe<span className="text-primary">.AI</span></span>
              </Link>

              {/* Center nav links */}
              <div className="hidden md:flex items-center gap-1">
                <NavDropdown label="Tools" items={toolLinks} />
                <Link href="/about" className="px-3 py-2 text-sm text-muted-foreground hover:text-foreground transition-colors rounded-md hover:bg-muted">
                  About
                </Link>
                <Link href="/mission" className="px-3 py-2 text-sm text-muted-foreground hover:text-foreground transition-colors rounded-md hover:bg-muted">
                  Mission
                </Link>
                <Link href="/pricing" className="px-3 py-2 text-sm text-muted-foreground hover:text-foreground transition-colors rounded-md hover:bg-muted">
                  Pricing
                </Link>
              </div>

              {/* Right-side CTAs */}
              <div className="flex items-center gap-3">
                <Button variant="ghost" size="sm" asChild><a href={APP_URL}>Sign in</a></Button>
                <Button size="sm" asChild><a href={APP_URL}>Get started</a></Button>
              </div>
            </div>
          </nav>
          <div className="pt-16">
            {children}
          </div>
          <footer className="border-t border-border bg-muted px-6 py-10 text-center text-[11.5px] leading-relaxed text-muted-foreground">
            <p className="mx-auto max-w-2xl">All results generated by FireSafe.AI are AI-produced and intended for reference purposes only. They do not constitute professional engineering advice, formal code interpretations, or official compliance determinations. Licensed professionals should always apply their own expertise, experience, and independent judgment before submitting, signing, or relying on any output. The engineer of record is responsible for verifying all results against applicable codes and standards. The Authority Having Jurisdiction (AHJ) retains final authority on all compliance matters.</p>
            <p className="mt-3">&copy; {new Date().getFullYear()} FireSafe.AI</p>
          </footer>
        </div>
      </body>
    </html>
  )
}
