import Link from 'next/link'
import Image from 'next/image'
import { toolNavLinks } from '@/lib/tools'

const companyLinks = [
  { name: 'About', href: '/about' },
  { name: 'Mission', href: '/mission' },
  { name: 'Pricing', href: '/pricing' },
  { name: 'Blog', href: '/blog' },
  { name: 'Contact', href: '/contact' },
]

export function SiteFooter() {
  const half = Math.ceil(toolNavLinks.length / 2)
  const toolColumns = [toolNavLinks.slice(0, half), toolNavLinks.slice(half)]

  return (
    <footer className="border-t border-border bg-muted">
      <div className="mx-auto max-w-6xl px-6 py-12">
        <div className="grid gap-10 sm:grid-cols-2 lg:grid-cols-[1.4fr_1fr_1fr_1fr]">
          {/* Brand */}
          <div>
            <Link href="/" className="flex items-center gap-2.5">
              <Image
                src="/logo-mark.svg"
                alt="FireSafe.AI logo"
                width={28}
                height={28}
                className="h-7 w-7"
              />
              <span className="text-sm font-bold tracking-tight">
                FireSafe<span className="text-primary">.AI</span>
              </span>
            </Link>
            <p className="mt-3 max-w-xs text-[13px] leading-relaxed text-muted-foreground">
              AI-powered fire protection engineering tools grounded in NFPA,
              IBC, and IFC standards. Built for engineers who stamp plans.
            </p>
          </div>

          {/* Tools columns */}
          {toolColumns.map((column, i) => (
            <div key={i}>
              <p className="mb-3 text-xs font-semibold uppercase tracking-widest text-foreground">
                {i === 0 ? 'Tools' : ' '}
              </p>
              <ul className="space-y-2">
                {column.map((item) =>
                  item.href.startsWith('http') ? (
                    <li key={item.name}>
                      <a
                        href={item.href}
                        className="text-[13px] text-muted-foreground transition-colors hover:text-foreground"
                      >
                        {item.name}
                      </a>
                    </li>
                  ) : (
                    <li key={item.name}>
                      <Link
                        href={item.href}
                        className="text-[13px] text-muted-foreground transition-colors hover:text-foreground"
                      >
                        {item.name}
                      </Link>
                    </li>
                  )
                )}
              </ul>
            </div>
          ))}

          {/* Company column */}
          <div>
            <p className="mb-3 text-xs font-semibold uppercase tracking-widest text-foreground">
              Company
            </p>
            <ul className="space-y-2">
              {companyLinks.map((item) => (
                <li key={item.name}>
                  <Link
                    href={item.href}
                    className="text-[13px] text-muted-foreground transition-colors hover:text-foreground"
                  >
                    {item.name}
                  </Link>
                </li>
              ))}
            </ul>
          </div>
        </div>

        <div className="mt-12 border-t border-border pt-8 text-center text-[11.5px] leading-relaxed text-muted-foreground">
          <p className="mx-auto max-w-2xl">
            All results generated by FireSafe.AI are AI-produced and intended
            for reference purposes only. They do not constitute professional
            engineering advice, formal code interpretations, or official
            compliance determinations. Licensed professionals should always
            apply their own expertise, experience, and independent judgment
            before submitting, signing, or relying on any output. The engineer
            of record is responsible for verifying all results against
            applicable codes and standards. The Authority Having Jurisdiction
            (AHJ) retains final authority on all compliance matters.
          </p>
          <p className="mt-3">&copy; {new Date().getFullYear()} FireSafe.AI</p>
        </div>
      </div>
    </footer>
  )
}
